### ISSUE TITLE
Permitir subir Foto/Video con el post

### ISSUE THREAD

**Issue by alu0100769579** [AlejandrDiaz/sytw-proyecto-socialull#10]

**Comment by alu0100769579** [comment]
Arreglar para que se pueda crear un nuevo post sin subir una imagen y que no de error.

`ReferenceError: /home/ubuntu/workspace/proyecto/views/index.ejs:161
    159|                                         
    160|                                         
 >> 161|                                         <% for(var i = 0; i < post.length; i++) { %>    
    162|                                                 
    163|                                             <% if(user.id == post[i].owner) { %> 
    164|                                                 <% var nombre_creador = user.local.name %>

post is not defined
    at eval (eval at compile (/home/ubuntu/workspace/proyecto/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:11:27)
    at returnedFn (/home/ubuntu/workspace/proyecto/node_modules/ejs/lib/ejs.js:580:17)
    at tryHandleCache (/home/ubuntu/workspace/proyecto/node_modules/ejs/lib/ejs.js:223:34)
    at View.exports.renderFile [as engine] (/home/ubuntu/workspace/proyecto/node_modules/ejs/lib/ejs.js:437:10)
    at View.render (/home/ubuntu/workspace/proyecto/node_modules/express/lib/view.js:135:8)
    at tryRender (/home/ubuntu/workspace/proyecto/node_modules/express/lib/application.js:640:10)
    at EventEmitter.render (/home/ubuntu/workspace/proyecto/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/home/ubuntu/workspace/proyecto/node_modules/express/lib/response.js:1008:7)
    at upload (/home/ubuntu/workspace/proyecto/app/routes.js:50:13)
    at Immediate.<anonymous> (/home/ubuntu/workspace/proyecto/node_modules/multer/lib/make-middleware.js:53:37)
    at runCallback (timers.js:676:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)`

**Comment by alu0100769579** [comment]
Solucionado
